######################################################################
# Automatically generated by qmake (2.01a) Sat May 18 09:07:08 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CQSpaceInvaders.h CSpaceInvaders.h CQSound.h CSDLSound.h
SOURCES += CQSpaceInvaders.cpp CQSound.cpp CSDLSound.cpp

unix:LIBS += -lSDL -lSDL_mixer
